#!/usr/bin/env bash

# my autostart for herbstluftwm 

config="~/.config/herbstluftwm/autostart"

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1    # Use alt as the main modifier
# Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn ${TERMINAL:-urxvt}

hc keybind $Mod-t spawn ~/.scripts/dmenu/themeselector.sh
hc keybind $Mod-x spawn ~/.scripts/dmenu/launcher.sh

# media keys
hc keybind XF86AudioRaiseVolume spawn ~/.scripts/hlwm/volumeup.sh
hc keybind XF86AudioLowerVolume spawn ~/.scripts/hlwm/volumedown.sh
hc keybind XF86AudioMute spawn ~/.scripts/hlwm/volumemute.sh
hc keybind XF86AudioPlay spawn ~/.scripts/hlwm/play.sh
hc keybind XF86AudioNext spawn ~/.scripts/hlwm/next.sh
hc keybind XF86AudioPrev spawn ~/.scripts/hlwm/prev.sh

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( Web Term Work Org Media Mail Steam Misc )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-d spawn dmenu_run´
# hc keybind $Mod-d spawn rofi

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# per-tag layouting

hc load Web '
(clients max:0 0x1800010)
'

hc load Term '
(split horizontal:0.450000:0
 (clients max:0)
  (split vertical:0.650000:1
   (clients max:0)
    (clients max:0)))
'

hc load Work '
(split horizontal:0.700000:0
 (clients max:1 0x1000007 0x4e0000a)
  (split vertical:0.500000:1
   (clients max:0 0xa02e1d)
    (clients max:0 0xa02af3)))
'

hc load Org '
(split horizontal:0.300000:0
 (split vertical:0.400000:0
  (clients max:0 0x2a00290)
   (split vertical:0.650000:0
    (clients max:0 0x2a00003)
     (clients max:0)))
      (clients max:0))
'

hc load Media '
(split horizontal:0.450000:0
 (clients max:0)
  (split vertical:0.400000:0
   (clients max:0)
    (clients max:0)))
'

hc load Mail '
(split horizontal:0.600000:0
 (clients max:2 0x2400010 0x240013b 0x2c4d1ac)
  (clients vertical:0))
'

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#FAAD45'
hc set frame_border_normal_color '#E12E72'
hc set frame_bg_normal_color ''
hc set frame_bg_active_color '#66000000'
hc set frame_border_width 0
hc set frame_border_inner_width 0
hc set always_show_frame 0
hc set frame_active_opacity 30 
hc set frame_normal_opacity 0 
hc set frame_bg_transparent 0
hc set frame_transparent_width 0
hc set frame_gap 15 

hc attr theme.padding_left 15
hc attr theme.active.color '#FAAD45'
hc attr theme.normal.color '#18859C'
hc attr theme.urgent.color '#FAB148'
hc attr theme.inner_width 0
hc attr theme.outer_witdh 0
hc attr theme.inner_color '#EB9605'
hc attr theme.border_width 5
hc attr theme.floating.border_width 10
hc attr theme.floating.outer_width 5
hc attr theme.floating.outer_color '#FE1F9C' 
hc attr theme.background_color '#59000000'

hc set window_border_width 0
hc set frame_padding 0
hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on 
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# app-spercific rules
hc rule class=Steam tag=Steam
hc rule class=Thunderbird tag=Mail

# unlock, just to be sure
hc unlock

herbstclient set tree_style '?| ++?-+'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/launch.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
start it on each monitor
"$panel" $monitor &
hc pad 0 "" "" 35
hc pad 0 0 
hc pad 0 "" 0
hc pad 0 "" "" "" 0
done

#############
#  Startup  #
#############

nitrogen --set-scaled --random  &
setxkbmap de &
compton &
xfce4-power-manager &
udiskie &
xrdb ~/.Xresources &
urxvtd -f &
lxpolkit &
dunst &

